# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-22 23:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170122_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='add',
        ),
        migrations.AddField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u9001\u65f6\u95f4'),
        ),
    ]
